### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by austindickey** [d-taylor6403/Project1#2]
Develop the UI

**Comment by austindickey** [comment]
![IMG_1098](https://user-images.githubusercontent.com/57920690/73708582-63caf080-46c4-11ea-9a64-11639ae3db2d.jpeg)

**Comment by JacobTate** [comment]
background image?
![drink](https://user-images.githubusercontent.com/57567558/73711812-b6f57100-46cd-11ea-809d-616b09d51409.jpg)

**Comment by austindickey** [comment]
The only problem with that is it can't be repeated. You want something that can be infinitely and seamlessly repeated so it becomes responsive to the web browser size.

Go to this site and try to find a background image:

https://www.toptal.com/designers/subtlepatterns/

**Comment by austindickey** [comment]
![basic-layout](https://user-images.githubusercontent.com/57920690/74089059-b3157600-4a62-11ea-9bf5-56d88bd5692c.png)
